## Exercise 1: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [209]:
import numpy as np
arr1 = np.asarray([1,2,3,4,5,6,7,8])
print("List to array:\n",arr1)
arr2 = np.asarray(((8,4,6),(1,2,3)))
print("Tuple to array:\n",arr2)

List to array:
 [1 2 3 4 5 6 7 8]
Tuple to array:
 [[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [208]:
arr1 = np.array([0,12,45.21,34,99.91])
print("Values in Fahrenheit degrees:\n",arr1)
print("Values in  Centigrade degrees:")
print(5*arr1/9-5*32/9)
    
    

Values in Fahrenheit degrees:
 [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [49]:
arr1 = np.array([1.1,2.2,3.2])
print("The size of the array:",len(arr1))
print("Length of one array element in bytes:",arr1.itemsize)
print("Total bytes consumed by the elements of the array:",arr1.nbytes)

The size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


## Exercise 4: Get the unique elements of an array

In [65]:
arr1 = np.array([10,10,20,20,30,30])
print("Original array:\n",arr1)
arr2 = set(arr1)
print("Unique elements of the above array:",arr2)
arr3= np.array([[1,1],[2,3]])
print("Original Array:\n",arr3)
x = np.unique(arr3)
print("Unique elements of the above array:",x)

Original array:
 [10 10 20 20 30 30]
Unique elements of the above array: {10, 20, 30}
Original Array:
 [[1 1]
 [2 3]]
Unique elements of the above array: [1 2 3]


## Exercise 5: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [211]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print("Original Array:",arr1)
arr1.reshape(3,3)
print("Change array shape to (3, 3)\n",arr1.reshape(3,3))

Original Array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3)
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [79]:
arr1= np.arange(2.5,6.5,0.13793103)
arr1

array([2.5       , 2.63793103, 2.77586206, 2.91379309, 3.05172412,
       3.18965515, 3.32758618, 3.46551721, 3.60344824, 3.74137927,
       3.8793103 , 4.01724133, 4.15517236, 4.29310339, 4.43103442,
       4.56896545, 4.70689648, 4.84482751, 4.98275854, 5.12068957,
       5.2586206 , 5.39655163, 5.53448266, 5.67241369, 5.81034472,
       5.94827575, 6.08620678, 6.22413781, 6.36206884, 6.49999987])

## Exercise 7: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [97]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
print("Array1",arr1)
print("Array2",arr2)
conv = np.stack((arr1,arr2),axis = 1)
print("Converted Array:\n",conv)

Array1 [10 20 30]
Array2 [40 50 60]
Converted Array:
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [188]:
arr1 = np.zeros((5,5))
arr1
print("Original Array:\n",arr1)
arr1+= np.arange(5)
print("Row values ranging from 0 to 4.\n",arr1)


Original Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [116]:
import numpy as np
x = np.arange(1,100)
n = x[(x%3 == 0)|(x%5==0)]
print(n[:1000])
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [201]:
x = np.arange(0,4,1)
print("One dimensional array:",x)
y = np.arange(4,8,1)
print("Two dimensional array:\n",np.stack((x,y)))
for a,b in np.nditer([x,y]):
    print(a,":",a)
    print(a,":",b)


    
    




One dimensional array: [0 1 2 3]
Two dimensional array:
 [[0 1 2 3]
 [4 5 6 7]]
0 : 0
0 : 4
1 : 1
1 : 5
2 : 2
2 : 6
3 : 3
3 : 7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [129]:
x = np.array([[[0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701, 0.38213418],[0.5097581,0.34528799, 0.1563123]]])
print("Original array:\n",x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x>0.5]=0.5
print(x)

Original array:
 [[[0.42436315 0.48558583 0.32924763]
  [0.7439979  0.58220701 0.38213418]
  [0.5097581  0.34528799 0.1563123 ]]]
Replace all elements of the said array with .5 which are greater than .5
[[[0.42436315 0.48558583 0.32924763]
  [0.5        0.5        0.38213418]
  [0.5        0.34528799 0.1563123 ]]]


## Exercise 12: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [146]:
import numpy as np
x = np.empty([0,0])
print("Empty array\n",x)
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
x = np.stack((arr1,arr2))
print("After adding two new arrays:\n",x)

Empty array
 []
After adding two new arrays:
 [[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [178]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
print("Original arrays:\n",arr1)
print(arr2)
print("Sequence of arrays along a new axis\n",np.stack((arr1,arr2)))
x = np.array([[1],[2],[3]])
y = np.array([[2],[3],[4]])
print("Original Array\n",x)
print("\n",y)
print("Sequence of arrays along a new axis:\n",np.vstack((x,y)))

Original arrays:
 [1 2 3]
[2 3 4]
Sequence of arrays along a new axis
 [[1 2 3]
 [2 3 4]]
Original Array
 [[1]
 [2]
 [3]]

 [[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
